"""Thread-safe, size-bounded raw WebSocket tick logging."""

import json
import re
import threading
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo


IST = ZoneInfo("Asia/Kolkata")
RAW_TICK_DIRECTORY = "raw_ticks"
MAX_TOTAL_BYTES = 2 * 1024 * 1024 * 1024
MAX_PART_BYTES = 100 * 1024 * 1024


def cleanup_raw_tick_files(base_directory=None):
    """Remove only files generated by the raw tick logger."""
    directory = Path(base_directory or Path.cwd()) / RAW_TICK_DIRECTORY
    if not directory.exists():
        return
    for path in directory.glob("*.jsonl"):
        if path.is_file():
            path.unlink()
    try:
        directory.rmdir()
    except OSError:
        pass


def _safe_filename(value):
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", str(value)).strip("._-")
    return cleaned or "instrument"


class RawTickLogger:
    def __init__(
        self,
        instruments=None,
        base_directory=None,
        max_total_bytes=MAX_TOTAL_BYTES,
        max_part_bytes=MAX_PART_BYTES,
    ):
        self.directory = Path(base_directory or Path.cwd()) / RAW_TICK_DIRECTORY
        self.directory.mkdir(parents=True, exist_ok=True)
        self.max_total_bytes = int(max_total_bytes)
        self.max_part_bytes = int(max_part_bytes)
        if self.max_total_bytes <= 0 or self.max_part_bytes <= 0:
            raise ValueError("Raw tick file-size limits must be greater than zero")

        self.symbols = {
            str(item["instrument_token"]): item.get("instrument_details", {}).get(
                "tradingsymbol", str(item["instrument_token"])
            )
            for item in (instruments or [])
        }
        self._part_numbers = {}
        self._lock = threading.Lock()
        self._total_bytes = sum(
            path.stat().st_size for path in self.directory.glob("*.jsonl") if path.is_file()
        )

    def log_tick(self, tick, received_at=None):
        """Append one complete tick and return the file it was written to."""
        received_at = received_at or datetime.now(IST)
        if received_at.tzinfo is None:
            received_at = received_at.replace(tzinfo=IST)
        received_at = received_at.astimezone(IST)

        token = str(tick.get("instrument_token", "unknown"))
        symbol = self.symbols.get(token, token)
        record = {
            "received_at": received_at.isoformat(),
            "instrument_token": tick.get("instrument_token"),
            "trading_symbol": symbol,
            "tick": tick,
        }
        line = (json.dumps(record, default=str, ensure_ascii=False, separators=(",", ":")) + "\n").encode("utf-8")
        if len(line) > self.max_total_bytes:
            raise ValueError("A single raw tick is larger than the total log-size limit")

        date_key = received_at.strftime("%m_%d")
        stream_key = (token, date_key)
        with self._lock:
            path = self._current_path(stream_key, symbol)
            if path.exists() and path.stat().st_size + len(line) > self.max_part_bytes:
                self._part_numbers[stream_key] += 1
                path = self._current_path(stream_key, symbol)

            self._make_space(len(line))
            with path.open("ab") as output:
                output.write(line)
            self._total_bytes += len(line)
            return path

    def _current_path(self, stream_key, symbol):
        token, date_key = stream_key
        if stream_key not in self._part_numbers:
            prefix = f"{_safe_filename(symbol)}_{_safe_filename(token)}_{date_key}_part"
            existing_parts = sorted(self.directory.glob(f"{prefix}*.jsonl"))
            if existing_parts:
                last_number = int(existing_parts[-1].stem.rsplit("part", 1)[-1])
                self._part_numbers[stream_key] = last_number
            else:
                self._part_numbers[stream_key] = 1
        part = self._part_numbers[stream_key]
        filename = (
            f"{_safe_filename(symbol)}_{_safe_filename(token)}_{date_key}_part{part:03d}.jsonl"
        )
        return self.directory / filename

    def _make_space(self, incoming_bytes):
        while self._total_bytes + incoming_bytes > self.max_total_bytes:
            files = sorted(
                (path for path in self.directory.glob("*.jsonl") if path.is_file()),
                key=lambda path: (path.stat().st_mtime_ns, path.name),
            )
            if not files:
                break
            oldest = files[0]
            removed_bytes = oldest.stat().st_size
            oldest.unlink()
            self._total_bytes -= removed_bytes
